#!/bin/sh
set -e

UNIT=service-monitor.service

if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
    deb-systemd-helper mask "$UNIT" >/dev/null || true
fi

if [ "$1" = "purge" ]; then
    deb-systemd-helper purge "$UNIT" >/dev/null || true
    deb-systemd-helper unmask "$UNIT" >/dev/null || true
fi

exit 0
