#!/bin/sh
set -e

UNIT=service-monitor.service

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
    deb-systemd-helper unmask "$UNIT" >/dev/null || true
    if deb-systemd-helper --quiet was-enabled "$UNIT"; then
        deb-systemd-helper enable "$UNIT" >/dev/null || true
    else
        deb-systemd-helper update-state "$UNIT" >/dev/null || true
    fi

    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        if [ -n "$2" ]; then
            deb-systemd-invoke try-restart "$UNIT" >/dev/null || true
        else
            deb-systemd-invoke start "$UNIT" >/dev/null || true
        fi
    fi
fi

exit 0
